import Head from 'next/head'
import Image from 'next/image'
import HeroSection from '../components/Waitlist-page/HeroSection'

export default function Home() {
  return (
    <div >
      <Head>
        <title>Waitinglist Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main >
      <HeroSection />
      </main>

     
    </div>
  )
}
